import React from "react";

const Reports = () => {
  return (
    <>
      <div>
        <div>
          <h1 className="text-center text-3xl mt-20 text-gray-700 font-bold">
            REPORTS
          </h1>
          <p className="ml-20 text-center w-[1100px] mt-5 text-gray-500 font-semibold text-xl">
            Several types of reports that can provide valuable insights into the
            performance of the business. Some of the most commonly used reports
            in Account management software include:
          </p>
        </div>
        <div className="flex gap-4 flex-col">
          <div className="flex gap-5">
            <div className="border border-gray-500 h-[300px] w-[600px] ml-20 mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Purchase report
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                This report provides an overview of purchases made by the
                business during a specific time period. It typically includes
                information such as the supplier name, purchase date, item
                description, quantity, unit price, and total cost. This report
                can help businesses track their spending on goods and services
                and identify areas for cost-saving.
              </p>
            </div>
            <div className="border border-gray-500 h-[300px] w-[600px] mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Purchase statement
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                A purchase statement is a financial document that provides a
                summary of all purchases made by a business during a specific
                time period. It typically includes information such as the name
                of the supplier, the date of the purchase, the items purchased,
                the quantities of each item, and the total cost of the
                purchases.
              </p>
            </div>
          </div>
          <div className="flex gap-5">
            <div className="border border-gray-500 h-[300px] w-[600px] ml-20 mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Sales report
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                This report provides an overview of sales made by the business
                during a specific time period. It typically includes information
                such as the customer name, sale date, item description,
                quantity, unit price, and total revenue. This report can help
                businesses track their sales performance, identify popular
                products or services, and forecast future sales.
              </p>
            </div>
            <div className="border border-gray-500 h-[300px] w-[600px] mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Item report
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                This report provides an overview of individual items sold or
                purchased by the business during a specific time period. It
                typically includes information such as the item name,
                description, stock level, unit price, and total sales or
                purchase value. This report can help businesses identify their
                most popular items, track stock levels, and forecast future
                demand.
              </p>
            </div>
          </div>
          <div className="flex gap-5">
            <div className="border border-gray-500 h-[300px] w-[600px] ml-20 mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Sales statement
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                A sales statement is a financial document that provides a
                summary of all sales made by a business during a specific time
                period. It typically includes information such as the name of
                the customer, the date of the sale, the items sold, the
                quantities of each item, and the total revenue generated by the
                sales. This statement is useful for tracking sales performance,
                analyzing trends, and identifying opportunities to increase
                revenue.
              </p>
            </div>
            <div className="border border-gray-500 h-[300px] w-[600px] mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                General statement
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                A general statement is a financial document that provides an
                overview of the financial position of a business at a specific
                point in time. It typically includes information such as the
                business’s assets, liabilities, equity, revenues, and expenses.
                This statement is useful for assessing the overall financial
                health of a business, identifying areas for improvement, and
                making strategic financial decisions.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div>
          <h1 className="text-center text-3xl mt-20 text-gray-700 font-bold">
            USER RIGHTS
          </h1>
          <p className="ml-20 text-center w-[1100px] mt-5 text-gray-500 font-semibold text-xl">
            User rights in grocery management software refer to the specific
            actions and tasks that a user is authorized to perform within the
            software. These rights are typically defined by the software
            administrator or system owner and are based on the user’s role
            within the organization.
          </p>
          <p className="ml-20 text-center w-[1100px] mt-5 text-gray-700 font-bold text-xl">
            Some common user rights in grocery management software may include:
          </p>
        </div>
        <div className="flex gap-4 flex-col">
          <div className="flex gap-5">
            <div className="border border-gray-500 h-[300px] w-[600px] ml-20 mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Access to specific modules
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                Users may be granted access to specific modules within the
                software based on their role within the organization. For
                example, a cashier may only be granted access to the point of
                sale module, while a manager may have access to inventory
                management, purchase management, and sales reports.
              </p>
            </div>
            <div className="border border-gray-500 h-[300px] w-[600px] mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Creating or deleting users
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                Users with administrative privileges may be authorized to create
                or delete user accounts within the software. This right is
                typically restricted to a small number of users with
                higher-level roles within the organization.
              </p>
            </div>
          </div>
          <div className="flex gap-5">
            <div className="border border-gray-500 h-[300px] w-[600px] ml-20 mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Editing or deleting data
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                Users may be authorized to edit or delete data within specific
                modules, such as sales data or inventory levels. This right is
                typically restricted to users with higher-level roles within the
                organization to ensure data accuracy and integrity.
              </p>
            </div>
            <div className="border border-gray-500 h-[300px] w-[600px] mt-10">
              <h1 className="text-white text-xl bg-red-400 text-center p-2 font-bold">
                Changing software settings
              </h1>
              <p className="w-[500px]  flex justify-between ml-10 mt-5 text-xl text-gray-500 ">
                Users with administrative privileges may be authorized to change
                software settings, such as tax rates or payment methods. This
                right is typically restricted to a small number of users with
                higher-level roles within the organization.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Reports;
